apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configserver
    spec:
      containers:
      - name: configserver
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }} 
        envFrom:
        - configMapRef:
            name: configserver
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"    

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app.kubernetes.io/name: configserver
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/name: configserver
