apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: usersvc-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usersvc 
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: usersvc
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usersvc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - name: usersvc
        image:  105420052274.dkr.ecr.us-east-1.amazonaws.com/usersvc 
        envFrom:
        - configMapRef:
            name: usersvc
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"    

---
apiVersion: v1
kind: Service
metadata:
  name: usersvc
  labels:
    app.kubernetes.io/name: usersvc
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/name: usersvc
