apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway 
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigateway
    spec:
      containers:
      - name: apigateway
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }} 
        envFrom:
        - configMapRef:
            name: apigateway
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"    

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  ports:
  - port: 9191
    targetPort: 9191
  selector:
    app.kubernetes.io/name: apigateway
